-- AlterTable: add dimensions and grid size to Warehouse
ALTER TABLE "Warehouse"
ADD COLUMN IF NOT EXISTS "width" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS "length" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN IF NOT EXISTS "height" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN IF NOT EXISTS "gridSize" INTEGER NOT NULL DEFAULT 1;
