-- AlterTable: add position and dimension fields to Shelf for layout updates
ALTER TABLE "Shelf"
ADD COLUMN IF NOT EXISTS "x" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "y" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "width" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "height" INTEGER NOT NULL DEFAULT 1;
